%YAML:1.0
---

# 修改参数时需要注意冒号后面要有一个空格，不然可能出错，程序无法读取

#####################分条带(分块)模式相关参数#####################

# 初始搜索窗口相关参数
# 如果相邻波段间y方向位移较大，则建议高度设置高一些
# 以确保能完全覆盖位移，有共同区域
# 波段间平移搜索窗口宽度
win_w: 2000
# 波段间平移搜索窗口高度
win_h: 5000

# 如果影像y方向变化比较明显，可以将条带高度设置小一些
# 但与此同时会导致计算量增加
# 扩展高度是指在待重采影像上分别向上向下扩展的范围
# 这样做的目的是保证冗余，避免出现条带间漏缝的情况
# 条带高度
stripe_height: 500
# 重采影像上，相对于条带高度，待重采范围的扩展部分
stripe_extension: 250
# 分块模式下，两个影像块之间的重叠像素范围
block_overlap: 80

# 分带(分块)模式特征提取相关参数
# surf算子阈值
surf_th: 1500
# surf算子阈值每次迭代改变量
surf_th_d: 250
# sift算子提取特征点数量阈值
sift_th: 10000
# orb算子提取特征点数量阈值
orb_th: 2000
# 每个条带提取的特征点数量上限
kps_max: 10000
# 每个条带提取的特征点数量下限
kps_min: 10
# 对于每个条带(分块)是否需要进行二次灰度拉伸的阈值，范围是0 - 255
# 若整个影像的灰度最大最小值之差大于80，则说明可能存在极亮或极暗部，
# 这会影像整体拉伸的效果，因此需要在每个条带再进行一次拉伸
# 如果小于阈值，说明灰度分布较为集中，拉伸会获得比较好的效果
stretch_th: 80

#####################分条带(分块)模式相关参数#####################


#####################全图模式相关参数############################

# 全图模式特征提取相关参数
# surf算子阈值
surf_th_global: 1200
# surf算子阈值每次迭代改变量
surf_th_d_global: 300
# sift算子提取特征点数量阈值
sift_th_global: 15000
# orb算子提取特征点数量阈值
orb_th_global: 5000
# 提取的特征点数量上限
kps_max_global: 50000
# 提取的特征点数量下限
kps_min_global: 700

#####################全图模式相关参数############################


#####################仿射模型相关参数############################

# 由于考虑变换近似于平移模型，因此以放射变换矩阵的(0,0),(1,1)元素作为条件
# 理想平移模型这两个元素大小应该都为1
# 仿射模型系数最小阈值
affine_min: 0.96
# 仿射模型系数最大阈值
affine_max: 1.04

#affine_min: 0.98
#affine_max: 1.02

#affine_min: 0.975
#affine_max: 1.025

#####################仿射模型相关参数############################


#####################去云模式相关参数############################

# 是否开启去云移动模式，1为开启，0为关闭
isCloudMode: 0
# 配准时去云的相关参数
# 膨胀的迭代次数
cloud_iter_num: 8
# 膨胀操作的卷积核大小
cloud_ksize: 9
# 判别云的灰度阈值，-1表示采用OTSU方法自动确定，其它值表示手动指定(0-255)
cloud_th: -1

#####################去云模式相关参数############################


#####################其它相关参数###############################

# 是否为调试模式，调试模式会输出每个条带(分块)的匹配结果
# 1表示开启，0表示关闭
isDebugMode: 0
# 波段排序是正序还是倒叙，1表示倒序，0表示正序
isReverse: 1
# 是否迭代基准影像，1表示开启，0表示关闭
# 注意如果是固定基准影像模式，程序启动的第一个参数是基准影像路径
# 若是迭代模式，启动的第一个参数则是基准影像所在文件夹
# 所以在这里修改模式后，也要记得修改程序启动参数
isIteration: 1
# 并行加速进程数
processNum: 6

#####################其它相关参数###############################